//TRACTORS
export const UPDATE_TRACTOR = 'UPDATE_TRACTOR'
export const CREATE_TRACTOR = 'CREATE_TRACTOR'
export const DELETE_TRACTOR = 'DELETE_TRACTOR'
export const FETCH_ALL_TRACTORS = 'FETCH_ALL_TRACTORS'

//DRIVERS
export const UPDATE_DRIVER = 'UPDATE_DRIVER'
export const CREATE_DRIVER = 'CREATE_DRIVER'
export const DELETE_DRIVER = 'DELETE_DRIVER'
export const FETCH_ALL_DRIVERS = 'FETCH_ALL_DRIVERS'
export const FETCH_DRIVER = 'FETCH_DRIVER'
